### ISSUE TITLE
thumbnail-no-Pillow.gif

### ISSUE THREAD

**Issue by PlayeRom** [frougon/FFGo#6]
I was using ffgo per some time. Later, to test the translation, I deleted the `~/.ffgo/config` file and then ffgo crashed:

```
WARNING: Nie można znaleźć domyślnego samolotu: c172p
FFGo 1.12.7 uruchomiony
Używając:
  - Python 3.8.10
  - CondConfigParser 1.0.5
  - Implementacja GeographicLib w Pythonie 3: wersja 1.50
  - MagneticField: GeographicLib version 1.50.1

Wykryta wersja FlightGear: brak
Traceback (most recent call last):
  File "./ffgo-launcher.py", line 14, in <module>
    ffgo.main.main()
  File "/media/romek/DATA/fgfs/FFGo/ffgo/main.py", line 190, in main
    res = run(master, params)
  File "/media/romek/DATA/fgfs/FFGo/ffgo/main.py", line 122, in run
    app = App(master, config, params)
  File "/media/romek/DATA/fgfs/FFGo/ffgo/gui/mainwindow.py", line 434, in __init__
    self.updateImage()
  File "/media/romek/DATA/fgfs/FFGo/ffgo/gui/mainwindow.py", line 2323, in updateImage
    self.image = self.getImage(aircraft)
  File "/media/romek/DATA/fgfs/FFGo/ffgo/gui/mainwindow.py", line 1185, in getImage
    image = PhotoImage(file=NO_PIL_PIC)
  File "/usr/lib/python3.8/tkinter/__init__.py", line 4064, in __init__
    Image.__init__(self, 'photo', name, cnf, master, **kw)
  File "/usr/lib/python3.8/tkinter/__init__.py", line 4009, in __init__
    self.tk.call(('image', 'create', imgtype, name,) + options)
_tkinter.TclError: couldn't open "/media/romek/DATA/fgfs/FFGo/ffgo/data/pics/thumbnail-no-Pillow.gif": no such file or directory
```

Interestingly, after created a file `thumbnail-no-Pillow.gif` (based on `thumbnail-no-Pillow.svg`) it launched correctly :)

**Comment by PlayeRom** [comment]
It's rather my misunderstanding of the project. I was running ffgo-launcher.py from the git repository, and it looks like I just didn't run the `make` command in the `ffgo/data/pics` directory which creates additional image files including my missing gif.

**Comment by frougon** [comment]
That's it, but you should use the _top-level_ Makefile.

In this project, generated files are not stored in the Git repository. That's why after cloning the repo or pulling changes that affect the sources of some of the generated files, you should run `make` from the top-level directory. The top-level Makefile will itself run `make` in all needed subdirectories, including `ffgo/data/pics`. BTW, this is what creates or updates the .mo files from their .po sources for l10n.

Once this `make` step has been performed, you can use `ffgo-launcher.py` without doing any “install” step. This is covered under “INSTALLATION FROM THE GIT REPOSITORY” in [docs/INSTALL/INSTALL_en](https://github.com/frougon/FFGo/blob/master/docs/INSTALL/INSTALL_en) (maybe a bit verbose...).

**Comment by PlayeRom** [comment]
Yes, right, thanks
